# 1. How to create a series from a list, numpy array and dict?

In [4]:
# importing necessary python libraries
import numpy as np
import pandas as pd

In [4]:
# inputs
word_list = list(['Nishan Limbu', 'Saru Limbu', 'Priya Limbu'])
numpy_array = np.arange(1, 11)
alphabet_dictionary = {'A': 0, 'B': 1, 'C': 2, 'D':3, 'E':4, 'F':5}

In [5]:
# creating a series from the above inputs
series1 = pd.Series(word_list)
series2 = pd.Series(numpy_array)
series3 = pd.Series(alphabet_dictionary)


In [6]:
# printing all the series
print(series1)
print(series2)
print(series3)

0    Nishan Limbu
1      Saru Limbu
2     Priya Limbu
dtype: object
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64
A    0
B    1
C    2
D    3
E    4
F    5
dtype: int64


# 2. How to combine many series to form a dataframe?

In [7]:
# input of two series
series1 = pd.Series(word_list)
series2 = pd.Series(numpy_array)

In [8]:
# using pandas DataFrame
df = pd.DataFrame(series1, series2).reset_index()
df

index            0
0      1   Saru Limbu
1      2  Priya Limbu
2      3          NaN
3      4          NaN
4      5          NaN
5      6          NaN
6      7          NaN
7      8          NaN
8      9          NaN
9     10          NaN

In [9]:
# using pandas DataFrame with a dictionary, gives specific columns name
df = pd.DataFrame({'col-1':series1, 'col-2':series2})
df.head()

col-1  col-2
0  Nishan Limbu      1
1    Saru Limbu      2
2   Priya Limbu      3
3           NaN      4
4           NaN      5

In [15]:
# uisng concat()
ser_df.head()

0  1
0  Nishan Limbu  1
1    Saru Limbu  2
2   Priya Limbu  3
3           NaN  4
4           NaN  5

# 3. How to get the items of series A not present in series B?

In [16]:
# input
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

In [18]:
ser1[~ser1.isin(ser2)]

0    1
1    2
2    3
dtype: int64

# 4. How to get the items not common to both series A and series B?

In [19]:
# input
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

In [22]:
# getting all the elements of ser1 that is not present on ser2
a_not_b = ser1[~ser1.isin(ser2)]
a_not_b

0    1
1    2
2    3
dtype: int64

In [23]:
# getting all the elements of ser2 that is not present on ser1
b_not_a = ser2[~ser2.isin(ser1)]
b_not_a

2    6
3    7
4    8
dtype: int64

In [29]:
# getting the result
result = pd.concat([a_not_b, b_not_a])
result

0    1
1    2
2    3
2    6
3    7
4    8
dtype: int64

In [34]:
# Another method:
# using numpy unions and intersection
u = pd.Series(np.union1d(ser1, ser2))  # union
i = pd.Series(np.intersect1d(ser1, ser2))  # intersection

# final result
result = u[~u.isin(i)]

result


0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

# 5. How to get useful infos

In [36]:
# Compute the minimum, 25th percentile, median, 75th, and maximum of serie.

In [42]:
# input
state = np.random.RandomState(100)  # creates a RandomState object in NumPy, which is used to generate random numbers
series1 = pd.Series(state.normal(10, 5, 25))  # state.normal(mean, std_dev, size) generates random numbers from a normal (Gaussian) distribution.
series1

0      1.251173
1     11.713402
2     15.765179
3      8.737820
4     14.906604
5     12.571094
6     11.105898
7      4.649783
8      9.052521
9     11.275007
10     7.709865
11    12.175817
12     7.082025
13    14.084235
14    13.363604
15     9.477944
16     7.343598
17    15.148663
18     7.809322
19     4.408409
20    18.094908
21    17.708026
22     8.740604
23     5.787821
24    10.922593
dtype: float64

In [43]:
# getting useful information (info)
series1.describe()

count                3
unique               3
top       Nishan Limbu
freq                 1
dtype: object

# 6. How to get frequency counts of unique items of a series?

In [44]:
# input
alphabet_list = list('abcdefgh')
alphabet_list

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']

In [45]:
# input
numbers = np.random.randint(8, size=30)
numbers

array([0, 2, 1, 0, 0, 4, 7, 6, 0, 3, 7, 1, 6, 3, 2, 0, 6, 4, 6, 7, 0, 5,
       3, 1, 4, 3, 5, 5, 1, 6], dtype=int32)

In [47]:
 # selecting elements from the list('abcdefgh') using the indices provided by np.random.randint.
sel_elements = np.take(alphabet_list, numbers)
sel_elements

array(['a', 'c', 'b', 'a', 'a', 'e', 'h', 'g', 'a', 'd', 'h', 'b', 'g',
       'd', 'c', 'a', 'g', 'e', 'g', 'h', 'a', 'f', 'd', 'b', 'e', 'd',
       'f', 'f', 'b', 'g'], dtype='<U1')

In [49]:
# creating a seriesA
seriesA = pd.Series(sel_elements)
seriesA

0     a
1     c
2     b
3     a
4     a
5     e
6     h
7     g
8     a
9     d
10    h
11    b
12    g
13    d
14    c
15    a
16    g
17    e
18    g
19    h
20    a
21    f
22    d
23    b
24    e
25    d
26    f
27    f
28    b
29    g
dtype: object

In [52]:
# counting the values
seriesA.value_counts()

a    6
g    5
d    4
b    4
h    3
e    3
f    3
c    2
Name: count, dtype: int64

# 7. How to convert a numpy array to a dataframe of given shape? (L1)

In [53]:
# Reshape the series ser into a dataframe with 7 rows and 5 columns

In [54]:
# input
numbers = np.random.randint(1, 10, 35)
numbers

array([9, 5, 6, 7, 1, 5, 1, 5, 8, 2, 5, 7, 8, 9, 5, 2, 7, 3, 5, 2, 7, 2,
       8, 8, 8, 6, 1, 3, 4, 8, 9, 1, 3, 4, 9], dtype=int32)

In [55]:
# creating a series
seriesA = pd.Series(numbers)
seriesA

0     9
1     5
2     6
3     7
4     1
5     5
6     1
7     5
8     8
9     2
10    5
11    7
12    8
13    9
14    5
15    2
16    7
17    3
18    5
19    2
20    7
21    2
22    8
23    8
24    8
25    6
26    1
27    3
28    4
29    8
30    9
31    1
32    3
33    4
34    9
dtype: int32

In [56]:
# converting a numpy array to a dataframe of given shape 7 rows and 5 columns
pd.DataFrame(np.array(seriesA).reshape(7, 5))

0  1  2  3  4
0  9  5  6  7  1
1  5  1  5  8  2
2  5  7  8  9  5
3  2  7  3  5  2
4  7  2  8  8  8
5  6  1  3  4  8
6  9  1  3  4  9

In [57]:
# Reshaping the series seriesA into a dataframe with 7 rows and 5 columns
pd.DataFrame(seriesA.values.reshape(7, 5))

0  1  2  3  4
0  9  5  6  7  1
1  5  1  5  8  2
2  5  7  8  9  5
3  2  7  3  5  2
4  7  2  8  8  8
5  6  1  3  4  8
6  9  1  3  4  9

# 8. How to find the positions of numbers that are multiples of 3 from a series?

In [58]:
# Find the positions of numbers that are multiples of 3 from ser.

In [63]:
# input
np.random.RandomState(100)

RandomState(MT19937) at 0x24A92CA7D40

In [64]:
# input
numbers = np.random.randint(1, 5, 10)
numbers

array([1, 3, 4, 3, 3, 1, 1, 2, 1, 3], dtype=int32)

In [66]:
# creating a series 
ser = pd.Series(numbers)
ser

0    1
1    3
2    4
3    3
4    3
5    1
6    1
7    2
8    1
9    3
dtype: int32

In [67]:
# using where clauses
result = ser.where(lambda x: x%3 == 0)
result

0    NaN
1    3.0
2    NaN
3    3.0
4    3.0
5    NaN
6    NaN
7    NaN
8    NaN
9    3.0
dtype: float64

In [68]:
# removing the NaN
result.dropna()

1    3.0
3    3.0
4    3.0
9    3.0
dtype: float64

In [69]:
# using argwhere
result = np.argwhere(ser%3 == 0)
result

array([[1],
       [3],
       [4],
       [9]])

# 9. How to extract items at given positions from a series

In [70]:
# From ser, extract the items at positions in list pos.

In [71]:
# input
alphabet_list = list('abcdefghijklmnopqrstuvwxyz')
alphabet_list

['a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z']

In [72]:
# creatinga  series
ser = pd.Series(alphabet_list)
ser

0     a
1     b
2     c
3     d
4     e
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object

In [74]:
# taking a positions
position = [0, 4, 8, 14, 20]
position

[0, 4, 8, 14, 20]

In [76]:
# using loc extracting the items
result = ser.loc[position]
result

0     a
4     e
8     i
14    o
20    u
dtype: object

In [77]:
# using series take to extract the items 
result = ser.take(position)
result

0     a
4     e
8     i
14    o
20    u
dtype: object

# 10. How to stack two series vertically and horizontally ?

In [79]:
# Stack ser1 and ser2 vertically and horizontally (to form a dataframe).

In [80]:
# input
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))

In [82]:
# Stack ser1 and ser2 vertically
result = pd.concat([ser1, ser2], axis=0) 
result

0    0
1    1
2    2
3    3
4    4
0    a
1    b
2    c
3    d
4    e
dtype: object

In [83]:
# Stack ser1 and ser2 horizontally
result = pd.concat([ser1, ser2], axis=1) 
result

0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e

# 11. How to get the positions of items of series A in another series B?

In [2]:
# Get the positions of items of ser2 in ser1 as a list.

In [5]:
# input
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])

In [8]:
# using numpy 'where' to get the positions of items of ser1 in another ser2
result = [np.where(i == ser1)[0].tolist()[0] for i in ser2]
result

[5, 4, 0, 8]

In [9]:
# using pandas index and get location
result = [pd.Index(ser1).get_loc(i) for i in ser2]
result

[5, 4, 0, 8]

# 12. How to compute differences of differences between consequtive numbers of a series?

In [11]:
# Difference of differences between the consequtive numbers of ser

In [12]:
# input
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])

In [13]:
# Desired Output
# [nan, 2.0, 3.0, 4.0, 5.0, 6.0, 6.0, 8.0]
# [nan, nan, 1.0, 1.0, 1.0, 1.0, 0.0, 2.0]

In [21]:
# using pandas diff()
ser.diff(periods = 1).tolist()


[nan, 2.0, 3.0, 4.0, 5.0, 6.0, 6.0, 8.0]

In [22]:
ser.diff(periods = 1).diff(periods = 1).tolist()

[nan, nan, 1.0, 1.0, 1.0, 1.0, 0.0, 2.0]